### ISSUE TITLE
BCDB schema  with Enum data type

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#243] opened 2019-11-17 13:39 UTC
Our BCDB schema must be able to handle ```None``` data type instead of enforcing the first element in the Enum as a default value 
example :
* I have Enum in our schema with the days of the week Sunday, Monday , Tuesday , .....
* I have an actor to handle the days' retrieval. 
* I want to retrieve all the days of the week by sending the days of the week enum as None.

In the current implementation, it is impossible as the ```schema in``` will set a default value from the enum

**Comment by xmonader** [comment] 2019-11-17 19:19
you need to define none as part of your enum if you don't want default values, that's by design. i'll set the issue to process_wontfix

**Closed** 2019-12-14 19:34 UTC
Labels: process_wontfix
