### ISSUE TITLE
myjobs server : doesn't change state of running job from new to running 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#134] opened 2019-10-17 15:13 UTC
I create job which it function  while  loop job which wait for 100 sec , 
at the beginning the state of process was new then ok , and never converted to running although it was running for 100 sec.
test.py file
```
import time
def just1():
    count = 0
    while(1):
        time.sleep(20)
        count=count+1
        if count == 5:
            print(count)
            break
```
j.servers.myjobs.schedule(test.just1) 

in the beginning and through 100 sec
![image](https://user-images.githubusercontent.com/24386802/67022282-47994880-f101-11e9-8e6d-94570b9fc257.png)

after 100 sec

![image](https://user-images.githubusercontent.com/24386802/67022416-7c0d0480-f101-11e9-8ffa-bab04560049b.png)

**Comment by grimpy** [comment] 2019-10-20 09:14
Did you start any worker?

**Comment by Dinaamagdy** [comment] 2019-10-20 09:17
Yes four workers

**Comment by BolaNasr** [comment] 2019-10-22 08:52
i can't reproduce this issue

**Comment by john-kheir** [comment] 2019-11-03 12:54
Never changed to running.. just went from new to ok

**Comment by rkhamis** [comment] 2019-11-20 09:44
closing this issue because behavior is updated

**Closed by rkhamis** 2019-11-20 09:44 UTC
Labels: type_bug
