### ISSUE TITLE
can't start threebot again after kill tmux session or stop server

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#560] opened 2020-02-20 10:22 UTC
## Steps 
- start threebot server 
j.servers.threebot.start(background)
- kill tmux session
    j.servers.tmux.kill()
- Try to start threebot server again 

## Issue 
![image](https://user-images.githubusercontent.com/24386802/74923231-15626500-53d9-11ea-8f7d-f3315c3fba05.png)

- happen although when I stop server with j.servers.threebot.get().stop() then start 
```
JSX> j.servers.threebot.get().stop()                                                                 
 * stop: lapis

 * stop: threebot_main

JSX> j.servers.threebot.get().start()                                                                
MARK THREEBOT IS STARTING
 * destroy: model:jumpscale.myjobs.action
 nid:1

 * stop: workers_1

 * stop: workers_2

Thu 20 13:19:37 ta/bcdb/BCDBModel.py - 389 - set                                : EXCEPTION: 
    Could not insert object, unique constraint failed:UNIQUE constraint failed: index_jumpscale_openresty_website.name
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreebotServer.py in start
    242    self.openresty_server.start()
/sandbox/lib/jumpscale/Jumpscale/servers/openresty/OpenRestyServer.py in start
    159    self._letsencrypt_configure()
/sandbox/lib/jumpscale/Jumpscale/servers/openresty/OpenRestyServer.py in _letsencrypt_configure
    120    listening_80 = self.websites.new("listening_80")
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in new
    30    self._autosave_deal(jsconfig, autosave, True)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _autosave_deal
    155    jsconfig._data.save()
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObjectRoot.py in save
    96    obj = self._model.set(self)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBDecorator.py in wrapper_queue_method
    63    res = func(*args, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py in set
    389    raise j.exceptions.Input("Could not insert object, unique constraint failed:%s" % e, data=obj)
-----------------------------

--DATA-----------------------
  ## jumpscale.openresty.website
  id:87
   - name                : listening_80
   - port                : 80
   - ssl                 : True
   - domain              :
   - path                :
   - mother_id           : 84
```

**Comment by rkhamis** [comment] 2020-02-27 18:39
could not reproduce. verified to be working after starting and stopping and even killing the processes

**Comment by Dinaamagdy** [comment] 2020-03-02 11:13
I get another error with same steps 
![image](https://user-images.githubusercontent.com/24386802/75671570-a19d4380-5c87-11ea-8c6d-0a269e987918.png)

**Comment by m-motawea** [comment] 2020-03-04 13:37
Fixed in PR: https://github.com/threefoldtech/jumpscaleX_core/pull/586

**Comment by hossnys** [comment] 2020-03-05 07:23
verified on branch unstable :

![Screenshot from 2020-03-05 08-39-49](https://user-images.githubusercontent.com/26298009/75954609-c0385000-5ebc-11ea-8f35-c781ba7dd38c.png)

**Closed by hossnys** 2020-03-05 07:23 UTC
Labels: type_bug
