### ISSUE TITLE
Corex: starting 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#301] opened 2019-12-02 13:13 UTC
When you try to start the server it throws an exception 
```install corex: 'j.servers.corex.install()```

even if the corex is intalled

**Comment by serboctor** [comment] 2019-12-02 13:25
We can't reproduce it anymore, and I checked the code and it seems fine.  I'll close this for now.

**Closed by serboctor** 2019-12-02 13:25 UTC
Labels: type_bug
