### ISSUE TITLE
use myhost dir for storing shared identity across 3bot containers on the same machine

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#644] opened 2020-03-22 13:15 UTC
use myhost dir for storing shared identities across 3bot containers on the same machine unless container is started explicitly with a different identity

- identities saved in /myhost/identites or suitable place
- when container installs it takes an identity as a flag or generates a new one
- when container installs it copies the identity from /myhost/identites into `/sandbox/cfg/keys/default`
- the original identity name is saved in `/sandbox/cfg/jumpscale_config.toml`

**Comment by rkhamis** [comment] 2020-03-22 13:21
I think what was intended here is that a default identity is chosen unless specified, but identities are all saved in the mounted myhost dir in all cases.

**Comment by Pishoy** [comment] 2020-03-25 08:13
got below error when i do below steps 
1 - copy a private key from exist container  `key.priv` and put in host in path /sandbox/var/containers/shared/keys/contidentity 
```
root@ubuntu-01:/sandbox/var/containers/shared/keys# ls contidentity/
key.priv

```
2 - start install jsx by this key 

`/tmp/jsx container-install --identity contidentity`

3 - got below error 
![image](https://user-images.githubusercontent.com/21987477/77515459-3ce99900-6e81-11ea-95ff-e0580b96f5f7.png)

**Comment by alichaddad** [comment] 2020-03-25 10:21
Should be fixed after this commit: https://github.com/threefoldtech/jumpscaleX_core/commit/9ab7f46d31c5cff5257bc2870b129c3fad9d664a. Contains docs for use as well.

**Comment by Pishoy** [comment] 2020-03-25 11:12
verified 
```
root@ubuntu-01:/sandbox/var/containers/shared/keys# ls contidentity/
key.priv  secret
root@ubuntu-01:/sandbox/var/containers/shared/keys# /tmp/jsx container-install --identity contidentity

root@3bot:/sandbox# ls -l /sandbox/myhost/keys/contidentity
total 8
-rw-r--r-- 1 root root 144 Mar 25 10:24 key.priv
-rw-r--r-- 1 root root  65 Mar 25 10:43 secret
root@3bot:/sandbox# ls -l /sandbox/myhost/keys/contidentity
total 8
-rw-r--r-- 1 root root 144 Mar 25 10:24 key.priv
-rw-r--r-- 1 root root  65 Mar 25 10:43 secret

``

**Closed by Pishoy** 2020-03-25 11:12 UTC
Labels: type_feature
