### ISSUE TITLE
bcdb tests fail 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#331] opened 2019-12-10 12:53 UTC
j.data.bcdb.test(name="base")                              
```                                                                                                                                                                              
base
Mon 09 14:56:09 ata/bcdb/BCDBMeta.py -  85 - _load                              : EXCEPTION: 
    storclient did not return  get(0) but still there is data, means corruption.
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py in test
    610    self._test_run(name=name)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _test_run
    53    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in __test_run
    154    self._code_run(name=name, path=path, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _code_run
    75    res = method(self=self, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/1_base.py in main
    209    test("RDB", schema, sqlite=False)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/1_base.py in test
    76    db = load(schema_url)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/tests/1_base.py in load
    44    db, model = self._load_test_model(type=name, schema=schema)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py in _load_test_model
    533    bcdb = j.data.bcdb.new(name="test", storclient=storclient, reset=True)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py in new
    398    if self.exists(name=name):
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py in exists
    254    if name in self.instances:
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py in instances
    157    bcdb = self._get(name, storclient)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py in _get
    374    self._instances[name] = BCDB(storclient=storclient, name=name)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in __init__
    64    self._init(**kwargs)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py in _init
    77    self.meta = BCDBMeta(self)
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBMeta.py in __init__
    56    self._load()
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBMeta.py in _load
    85    data=self._bcdb.storclient,
-----------------------------

--DATA-----------------------
  ## .rdb.client
   - name                :
   - nsname              :
   - type                : RDB
-----------------------------

None
```

**Comment by rkhamis** [comment] 2019-12-11 14:53
duplicate of https://github.com/threefoldtech/jumpscaleX_core/issues/340

**Closed by rkhamis** 2019-12-11 14:53 UTC
Labels: priority_critical, type_bug
