### ISSUE TITLE
Unhandled exception in 3sdk

### ISSUE THREAD

**Issue by everhusk** [threefoldtech/jumpscaleX_core#900] opened 2020-06-24 02:26 UTC
<img width="699" alt="Screenshot 2020-06-23 at 10 11 35" src="https://user-images.githubusercontent.com/4977840/85490792-66a97d80-b5a0-11ea-97fa-ea4f4569b4bb.png">

Happens on almost every keypress when creating a container or typing any text. Doesn't affect functionality, just annoying to be interrupted so frequently when typing.

**Comment by grimpy** [comment] 2020-06-24 08:20
duplicate of https://github.com/threefoldtech/jumpscaleX_core/issues/884

will be part of 10.7

**Closed by grimpy** 2020-06-24 08:20 UTC
Labels: type_bug
