### ISSUE TITLE
[INSTALLATION] Silent installation is not working

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#410] opened 2020-01-09 14:30 UTC
### Steps
See installation steps [here](https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/Installation#jumpscalex-installation-instructions) and instead of the install step do that (for silent installation)
```bash
/tmp/jsx configure -s --secret test
/tmp/jsx container-install -s
```
### Result
```bash
- get sandbox repos from git
Cloning into 'jumpscaleX_builders'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Thu 09 12:30:29 /tmp/InstallTools.py -4325 - repos_get                          : EXCEPTION: 
    NameError("name 'j' is not defined",)
--TRACEBACK------------------
./jsx.py in <module>
    988    cli()
./jsx.py in install
    296    installer.install(sandboxed=False, force=force, gitpull=pull, prebuilt=prebuilt, branch=branch)
/tmp/InstallTools.py in install
    4241    BaseInstaller.install(sandboxed=sandboxed, force=force, branch=branch)
/tmp/InstallTools.py in install
    3761    ji.repos_get(pull=False, branch=branch)
/tmp/InstallTools.py in repos_get
    4325    j.shell()
-----------------------------

```

**Comment by waleedhammam** [comment] 2020-01-13 12:24
Also I encountered a bug when the installer clones the `home` repo it tries to clone it with the branch I'm using `development` which not exists

**Comment by serboctor** [comment] 2020-01-15 10:52
probably duplicate of https://github.com/threefoldtech/jumpscaleX_core/issues/432 I'll test again after @BolaNasr  is done

**Comment by waleedhammam** [comment] 2020-01-15 11:50
> @waleedhammam's comment is duplicate of #432.

Yeah exactly, I encountered it 2 days ago or so

**Comment by serboctor** [comment] 2020-01-15 17:20
https://github.com/threefoldtech/jumpscaleX_core/commit/1f0785c2afe2122c7b24ebf7cb5a785189e2165e#diff-e31a5f784e627e9104be5c9cc9d68cf4L2883
The change of this line broke the silent installation. It implies that we now support a separation between silent installation and using an ssh agent. However, this is not true because of several reasons:
1) Even if you call `jsx configure --no-sshagent`, when you call `container-install`, it calls the configure function again and resets the ssh-agent value to True.
2) Even if we modify `container-install` to allow setting `ssh-agent` to False, the installation will not work because we depend on the ssh-agent to execute commands on the docker.

Our installation is in general very buggy and needs to be thoroughly re-speced and refactored.  In the meantime, I readded the line linked at the beginning of the comment to allow silent installations to automatically use http. https://github.com/threefoldtech/jumpscaleX_core/compare/development_installer_nosshagent

**Comment by Dina-Abd-Elrahman** [comment] 2020-01-20 10:16
- verified.

**Closed by Dina-Abd-Elrahman** 2020-01-20 10:16 UTC
Labels: type_bug
