### ISSUE TITLE
3bot takes too long to start after container-install

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#648] opened 2020-03-22 18:33 UTC
takes too long to start because of installing too many dependencies after container-install

**Comment by rkhamis** [comment] 2020-03-23 09:37
part of https://github.com/threefoldtech/home/issues/585

**Comment by ahelsayd** [comment] 2020-03-23 11:25
commit https://github.com/threefoldtech/jumpscaleX_core/commit/e53449c568485bf2559b869ee3de4946ade52dad

**Comment by ahelsayd** [comment] 2020-03-23 18:45
blocked on this https://github.com/threefoldtech/home/issues/585
part of the problem is image threefoldtech/3bot2 was not build correctly and i need to build it again using the ```container builder``` command which is broken and should be fixed by the above issue

**Comment by rkhamis** [comment] 2020-03-30 13:33
Fixed by kristof

**Closed by rkhamis** 2020-03-30 13:33 UTC
Labels: type_bug
